%%
run('prioruncertainty.m')

totaltime = 0.5e6 * 365.25 * 24; % Half a million years (in hours)

SETUP = struct(                         ... 
    'L',            100,                 ...
    'W',            200,                ...
    'W_m',          40e3,        ...
    'dt',           7e4,                  ...
    't1',           totaltime*.25,                ...
    't2',           totaltime*.50,            ... 
    't3',           totaltime*.75,             ... 
    't4',           totaltime,            ... 
    'saveInterval', 5,                  ...
    'showPlot',     false                ...
    ); 

dtMax = maxTimeStep(SETUP,PRIOR);
disp(['Max time step: ',num2str(dtMax)])
disp(['Used time step: ',num2str(SETUP.dt)])

%%
NAME = 'Data/dev';
runMonteCarlo(SETUP, PRIOR, NAME, 1)








