PRIOR = struct(                          ...
    'water_supply', 11.3267,            ... 
    'sed_supply',   17.451,            ...
    'sed_density',  2.6348e3,             ...
    'SLR',          1.25e-4,                  ... %mm/hr????
    'N0',           3,                  ...
    'h0',           50,                 ...
    'Np_water',     1000,               ...
    'Np_sed',       1000,               ...
    'u_max_coef',   2,                  ...
    'hB_coef',      1,                  ...
    'theta_water',  1,                  ...
    'theta_sand',   2,                  ...
    'theta_mud',    1,                  ...
    'fbedload',     .5,                ...
    'beta',         3,                  ...
    'lambda',       1,                  ...
    'udm_coef',     .45,                ...
    'uem_coef',     1.75,                ...
    'ues_coef',     1.25,               ...
    'alpha',        0.1,                ...
    'Nsmooth',      5,                 ...
    'Csmooth',      .8,              ...
    'omega_sfc',    0.1,                ...
    'omega_flow',   0.9,                 ...
    'itermax',      1,                  ...
    'S0',           2e-2,             ...
    'gamma',        0.05,                ...
    'H_SL',         0                   ...
    );